#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill $HOME/.config/bspwm/wallpaper.png &
wmname LG3D &
vmware-user-suid-wrapper &
setxkbmap latam
~/.config/polybar/launch.sh &

#bspc config pointer_modifier mod1
bspc monitor -d I II III IV V VI VII IX X

bspc config border_width 2
bspc config window_gap 8
bspc config top_padding 20
#bspc config bottom_padding -6
bspc config left_padding 0
bspc config right_padding 0

bspc config border_width         1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#bspc rule -a Caja desktop='^2' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a Cherrytree desktop='^3'
bspc rule -a Firefox-esr desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Thunar desktop='^2' follow=on
bspc rule -a burp-StartBurp: state=floating desktop='^3'
bspc rule -a XTerm: state=floating
bspc rule -a feh: state=floating

#margen sin enfocar
#bspc config normal_border_color "#9a9797"
#Color del borde de una ventana enfocada de un desenfocado monitor
bspc config active_border_color "#ffffff"
#margen del panel
bspc config focused_border_color "#8FBCBB"
#ctrl+windows+alt
bspc config presel_feedback_color "#8FBCBB"
