#! /bin/sh

sxhkd &
feh --bg-fill /home/noroot/Images/wallpaper.png &
#feh --bg-fill /home/noroot/Imágenes/monte.png &
wmname LG3D &
#~/.config/polybar/launch.sh &
#xfce4-clipman &

bspc config pointer_modifier mod1
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 6
bspc config top_padding -6
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

#bspc config border_width         1
#bspc config window_gap           6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#bspc rule -a Caja desktop='^2' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a Cherrytree desktop='^3'
bspc rule -a Firefox-esr desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a burp-StartBurp: state=floating desktop='^3'
bspc rule -a XTerm: state=floating
bspc rule -a feh: state=floating

#margen sin enfocar
#bspc config normal_border_color "#9a9797"
#Color del borde de una ventana enfocada de un desenfocado monitor
bspc config active_border_color "#efec20"
#margen del panel
bspc config focused_border_color "#ffffff"
#ctrl+windows+alt
bspc config presel_feedback_color "#05b400"

#~/.config/polybar/./launch.sh
polybar -c /home/noroot/.config/polybar/config.ini
vmware-user-suid-wrapper &
